POST http://localhost:3333/subscriptions
Content-Type: application/json

// em "error" no send request aparece unsupported media type
// precisamos informarque está enviando no formato JSON para REST API

// em questão de validação

{
    "name": "Usuário Indicado 4",
    "email": "indicado4@hotmail.com.br",
    "referrer": "41900b7b-ed60-4d95-a913-65082e716c16"
}

### 


GET http://localhost:3333/invites/15f1f619-23b2-4502-a72e-f4086481293b

###

GET http://localhost:3333/subscribers/15f1f619-23b2-4502-a72e-f4086481293b/ranking/clicks

###

GET http://localhost:3333/subscribers/15f1f619-23b2-4502-a72e-f4086481293b/ranking/count

###

GET http://localhost:3333/subscribers/15f1f619-23b2-4502-a72e-f4086481293b/ranking/position

###
GET http://localhost:3333/ranking
